### PR TITLE
feat(angular): config input

### PR DESCRIPTION
**Pull request by vltansky**
```html
<swiper [config]="{ slidesPerView: 3 }" [spaceBetween]="50">
    <ng-template swiperSlide>Best slide ever 2</ng-template>
    <ng-template swiperSlide>Best slide ever 2</ng-template>
    <ng-template swiperSlide>Best slide ever 2</ng-template>
    <ng-template swiperSlide>Best slide ever 2</ng-template>
    <ng-template swiperSlide>Best slide ever 2</ng-template>
  </swiper>
```

### CODE REVIEW

**Comment by vltansky** [comment]
@nolimits4web I'm not sure if it should be merged. 
If yes I guess this functionality should be implemented in other frameworks too.

**Comment by nolimits4web** [comment]
I am not sure too :) In other frameworks it is not needed as it is possible to use object spread there:
```
const params = {
  slidesPerView: 1,
  spaceBetween: 50,
}

// and then just
<Swiper { ...params }>...</Swiper>
```
If Angular doesn't allow this, then I think it will be useful. Is it ready to be merged?

**Comment by vltansky** [comment]
Even checked to be sure... Nope it's not possible
https://github.com/angular/angular/issues/14545

It is ready to be merged. It will probably have some improvements in thumbs & controller PR.

After swipers angular library, I feel that I must learn Vue or React :))

**Comment by nolimits4web** [comment]
Merged, thanks!

**Pull request merged**
