### PR TITLE
feat(angular): events types

### PR DESCRIPTION
**Pull request by vltansky**
exported as `SwiperNgEvents`.
Have better naming suggestion?

### CODE REVIEW

**Comment by nolimits4web** [comment]
Let's rename it to just `Events`

**Comment by vltansky** [comment]
Difficult for autoimport?

**Comment by nolimits4web** [comment]
Then `SwiperEvents` ? :)

**Comment by vltansky** [comment]
then it would be the same as Cores Swiper Events:)
Maybe `SwiperEventsParams` and export it from `swiper/types` instead of angular?

**Comment by nolimits4web** [comment]
> then it would be the same as Cores Swiper Events:)

That is not a problem, as you anyway import it from `swiper/angular` and it is not needed anywhere else except in Angular

**Comment by nolimits4web** [comment]
Maybe then just `EventsParams`

**Comment by nolimits4web** [comment]
Can you also send a PR for Angular docs?

**Comment by vltansky** [comment]
done
https://github.com/nolimits4web/swiper-website/pull/234

**Pull request merged**
