### PR TITLE
Support for execution under Node (Server Side Rendering). Does not touch the DOM or register global varialbe if under Node. Fixes #1541

### LINKED ISSUE #1541: server bug: navigator is not defined
Usecase:

````
import Swiper from "swiper"

export default React.createClass({
   componentDidMount: function(){
      const swiper = new Swiper( this.refs.container, this.props.settings );
   },
});
````

If you try to render this on server side you'll get: `ReferenceError: navigator is not defined`

Problem: Swiper is not isomorphic.

### PR DESCRIPTION
**Pull request by hheexx**

### CODE REVIEW

**Comment by Stas-Buzunko** [comment]
@hheexx installed your pull but still get error
image

**Comment by Neophy7e** [comment]
@Stas-Buzunko you need first to rebuild the lib it's explained in the Readme

**Comment by hheexx** [comment]
@Stas-Buzunko try now
@Neophy7e I commited artifects now

**Comment by tconroy** [comment]
@nolimits4web any chance we could get this updated/merged in? Lots of interest in using this in a server-side rendered app.

**Comment by krzysiek1507** [comment]
+1 for it!

**Comment by nolimits4web** [comment]
Closing as outdated and incompatible with current version of Swiper

**Comment by Xiao4** [comment]
Move to other swiper lib as not ssr-safe and @nolimits4web do not care about this

**Pull request closed without merging**
