### PR TITLE
[proposal] add all contributors

### PR DESCRIPTION
**Pull request by vltansky**
Also all contributors bot can be added: https://allcontributors.org/docs/en/bot/overview

I've added all contributors with badge `code`:
```
> npx all-contributors check

Missing contributors in .all-contributorsrc:
    greenkeeper[bot]
```
to add user / badge:
```
npx all-contributors add nolimits4web ideas
```

badges: https://allcontributors.org/docs/en/emoji-key

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks!

**Comment by vltansky** [comment]
@all-contributors please add @nolimits4web for maintenance

**Comment by nolimits4web** [comment]
@all-contributors please add @nolimits4web for maintenance

**Comment by nolimits4web** [comment]
@all-contributors please add @nolimits4web for maintenance

**Pull request merged**
