### PR TITLE
slidesPerOnce

### PR DESCRIPTION
**Pull request by BARTlab**
forced number of slides that can be changed at one time

### CODE REVIEW

**Comment by nolimits4web** [comment]
How is it different from `slidesPerGroup`?

**Comment by BARTlab** [comment]
`slidesPerGroup` just informs us about how many slides will be rendered within one group. When swiping and no matter if it is long or short, I can swipe more than one slide at a time.
When I need, I can swipe strictly one slide at a time

**Comment by nolimits4web** [comment]
`slidesPerGroup` means amount of slides that will be changed per one swipe/slideNext/Prev. `slidesPerGroup: 3` mean it will slide by 3 slides

**Comment by BARTlab** [comment]
demo:
https://codesandbox.io/s/swiper-js-forked-eqqo0?file=/src/index.js

video:
https://www.dropbox.com/s/v5cegeqq71axlhz/swiper_one_slide-2021-11-08_16.11.34.mkv

**Comment by nolimits4web** [comment]
Not sure what you wanted to show but your video and demo uses `slidesPerGroup: 1` which is the default value and doesn't have any effect. Change it to `2` and it will slide 2 slides at a time

**Comment by BARTlab** [comment]
the video shows that a value of 1 scrolls more than 1 slide (second attempt)

ru:
на видео видно, что при значении `slidesPerGroup: 1` прокручивается более 1 слайда (вторая попытка)

**Pull request closed without merging**
