### PR TITLE
add property realIndex

### PR DESCRIPTION
**Pull request by navyxie**
add property realIndex:
```js
s.updateRealIndex = function(){
    s.realIndex = s.slides.eq([s.activeIndex]).attr('data-swiper-slide-index') || s.activeIndex;
};
```

from issue : [Need a way to get the accurate activeIndex in loop mode](https://github.com/nolimits4web/Swiper/issues/1696)

from stackoverflow : [iDangero.us Swiper slide count when loop is true](http://stackoverflow.com/questions/29348926/idangero-us-swiper-slide-count-when-loop-is-true/36880901#36880901)

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks good, thanks. But PR shoud be done only to `src/js/core.js` file without files in dist/ folder. Also:
```
s.slides.eq([s.activeIndex])
```
should be just
```
s.slides.eq(s.activeIndex)
```
Can you do these changes and i will merge it? Otherwise i'll merge it later manually

**Comment by navyxie** [comment]
@nolimits4web  It's ok ,thanks.

**Comment by nolimits4web** [comment]
Merged, thanks

**Comment by pvaladez** [comment]
Hey not sure if this is by design, but the realIndex property is a string - could it instead be an integer?

**Pull request merged**
