### PR TITLE
New gulp tasks for minified dist

### PR DESCRIPTION
**Pull request by PRDeving**

### CODE REVIEW

**Comment by nolimits4web** [comment]
Sorry, didn't get it. Why is this task, if such min files are already in `dist/` folder?

**Comment by PRDeving** [comment]
dist/ folder weights 1.5Mb, with my gulp tasks it weights just 388Kb

**Comment by nolimits4web** [comment]
But you can just remove unnecessary files, also this folders structure update can break many existing projects with update, people will have to change paths. So i can't accept it at the moment

**Comment by nolimits4web** [comment]
Closing as outdated and incompatible with current version of Swiper

**Pull request closed without merging**
