### PR TITLE
fix package.json exports for typescript

### LINKED ISSUE #6508: Export typings correctly in package.json
### Clear and concise description of the problem

I noticed when using the new `bundler` option under `moduleResolution` in TypeScript 5, that swiper's type declarations are not compatible:

```
Could not find a declaration file for module 'swiper'. '/node_modules/swiper/swiper.esm.js' implicitly has an 'any' type.
There are types at '/node_modules/swiper/swiper.d.ts', but this result could not be resolved when respecting package.json "exports". The 'swiper' library may need to update its package.json or typings.
```

### Suggested solution

Correctly link the declaration files, as seen in [a similar pull request here](https://github.com/gxmari007/vite-plugin-eslint/pull/60). Updating the `package.json` will make this package compatible with the new `moduleResolution` option.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

### PR DESCRIPTION
**Pull request by Tarik02**
Fixes #6508

### CODE REVIEW

**Comment by nolimits4web** [comment]
I will schedule it for next major v10 release, as i guess it can bring breaking changes

**Comment by hakimLyon** [comment]
Hi @nolimits4web , @Tarik02. Before the release of v10, have other users of the 'swiper' library found any temporary solutions or alternatives to work around this issue? I'm interested in any suggestions or tips that could help while waiting for the next release.

**Comment by Tarik02** [comment]
> Hi @nolimits4web , @Tarik02. Before the release of v10, have other users of the 'swiper' library found any temporary solutions or alternatives to work around this issue? I'm interested in any suggestions or tips that could help while waiting for the next release.

Hi. I just used yarn patch to apply these changes myself.

**Comment by gabrielzfr** [comment]
> Fixes #6508

thx bro you´re awesome

**Comment by RamiJS** [comment]
thank you, this issue really caused me a headache

**Review by MaykonFelix — APPROVED** [review]
Thank you very much, everything worked fine here.

**Pull request merged**
