### PR TITLE
Fixed Mouse Drag Events for touch Screen Laptops / desktops like Surface

### PR DESCRIPTION
**Pull request by mhshakouri**
It fixes the bug where touch screen enabled Laptops/Desktops like Surface from Microsoft cannot drag and swipe slides/scrollbars with mouse/touchpad and they can only use the touchscreen.

I just edited two files form the source:
One change at [src/components/core/events/index.js line 35 and 83](https://github.com/nolimits4web/Swiper/compare/master...mhshakouri:iss2425?expand=1#diff-c5c34dde1843326dabe829f3abde8511)

and another one at:
[src/components/scrollbar/scrollbar.js line 221](https://github.com/nolimits4web/Swiper/compare/master...mhshakouri:iss2425?expand=1#diff-9ee2261d4ef777f6e1faa70f7d24935d)

This pull request is related to issue:
[Issue2425](https://github.com/nolimits4web/Swiper/issues/2425)

### CODE REVIEW

**Comment by nolimits4web** [comment]
Hi, this doesn't make much sense:
```js
if (Support.touch && !Device.ios && !Device.android && Device.desktop) {
        target.addEventListener('mousedown', swiper.onTouchStart, capture);
        target.addEventListener('mousemove', swiper.onTouchMove, capture);
        target.addEventListener('mouseup', swiper.onTouchEnd, capture);
        document.addEventListener('mousemove', swiper.onTouchMove, capture);
        document.addEventListener('mouseup', swiper.onTouchEnd, capture);
      }
```
If it supports touch to addition to pointerEvents, then it probably must be `touchstart`, `touchmove`, `touchend` instead of mouse events. Also, no sense to add events to both target and document. If there touch events then it should be just:
```js
        target.addEventListener('touchstart', swiper.onTouchStart, capture);
        target.addEventListener('touchmove', swiper.onTouchMove, capture);
        target.addEventListener('touchend', swiper.onTouchEnd, capture);
```
Can you please check it with such events?

**Comment by mhshakouri** [comment]
You were right, this code should not be placed there, where the if condition is (process.env.target !== Desktop) and also it had nothing to do with code block it was written in. I just coded it there becuz it worked.
In this new push I replaced it after that if condition, since it is a separate logic it self.
I removed the extra doc event listeners.

The thing about mouse events rather than touch events is, if you dont add mouse events for a touch screen enabled desktop like surface devices, user would not be able to do any thing with the mouse in certain browsers like chrome. They can only work with the swiper instance with touch screen events.

I have placed a condition for such devices which support touch and meanwhile they are Device.desktop, so that if the simulateTouch parameter is active (true) it does add the mouse events else it does not.

**Comment by nolimits4web** [comment]
Sorry, not it went wrong. I don't understand, how this (what is in the current version):
```
if (Support.touch) {
  const passiveListener = touchEvents.start === 'touchstart' && Support.passiveListener && params.passiveListeners ? { passive: true, capture: false } : false;
  target.addEventListener(touchEvents.start, swiper.onTouchStart, passiveListener);
  target.addEventListener(touchEvents.move, swiper.onTouchMove, Support.passiveListener ? { passive: false, capture } : capture);
  target.addEventListener(touchEvents.end, swiper.onTouchEnd, passiveListener);
}
if ((params.simulateTouch && !Device.ios && !Device.android) || (params.simulateTouch && !Support.touch && Device.ios)) {
  target.addEventListener('mousedown', swiper.onTouchStart, false);
  document.addEventListener('mousemove', swiper.onTouchMove, capture);
  document.addEventListener('mouseup', swiper.onTouchEnd, false);
}

```

different from what you have pushed in addition:

```
if (Support.touch && Device.desktop) {
     if (params.simulateTouch === true) {
       target.addEventListener('mousedown', swiper.onTouchStart, capture);
       target.addEventListener('mousemove', swiper.onTouchMove, capture);
       target.addEventListener('mouseup', swiper.onTouchEnd, capture);
     }
   }
}
```

**Comment by nolimits4web** [comment]
Actually in source code now, for Chrome:
```js
if (Support.pointerEvents || Support.prefixedPointerEvents) {
  // Chrome skips this part, it is IE/Edge only
  target.addEventListener(touchEvents.start, swiper.onTouchStart, false);
  (Support.touch ? target : document).addEventListener(touchEvents.move, swiper.onTouchMove, capture);
  (Support.touch ? target : document).addEventListener(touchEvents.end, swiper.onTouchEnd, false);
} else {
  // Chrome goes here
  if (Support.touch) {
    // should match condition and touch events will be assigned
    const passiveListener = touchEvents.start === 'touchstart' && Support.passiveListener && params.passiveListeners ? { passive: true, capture: false } : false;
    target.addEventListener(touchEvents.start, swiper.onTouchStart, passiveListener);
    target.addEventListener(touchEvents.move, swiper.onTouchMove, Support.passiveListener ? { passive: false, capture } : capture);
    target.addEventListener(touchEvents.end, swiper.onTouchEnd, passiveListener);
  }
  if ((params.simulateTouch && !Device.ios && !Device.android) || (params.simulateTouch && !Support.touch && Device.ios)) {
    // match condition and mouse events will be assigned in addition
    target.addEventListener('mousedown', swiper.onTouchStart, false);
    document.addEventListener('mousemove', swiper.onTouchMove, capture);
    document.addEventListener('mouseup', swiper.onTouchEnd, false);
  }
}
```

So which exact part of this doesn't actually work?

**Comment by dgmdata** [comment]
I'm rewriting my application from 3.4.2 to 4.1.0.

Also had same behavior on Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)) on Windows 8.1.

Mouse drag for slide was not working (IE, Firefox OK)

I have a TOUCH SCREEN laptop.

I've change the swiper.js code to make this work:

# 2943
  // Touch Events
  {
    if (Support.pointerEvents || Support.prefixedPointerEvents) {
      target.addEventListener(touchEvents.start, swiper.onTouchStart, false);
      (Support.touch ? target : doc).addEventListener(touchEvents.move, swiper.onTouchMove, capture);
      (Support.touch ? target : doc).addEventListener(touchEvents.end, swiper.onTouchEnd, false);
	    
        // ADD 3 LINES FROM #2957
	target.addEventListener('mousedown', swiper.onTouchStart, false);
        doc.addEventListener('mousemove', swiper.onTouchMove, capture);
        doc.addEventListener('mouseup', swiper.onTouchEnd, false);

Not sure if it's a good hack. 

Please advice

**Comment by mhshakouri** [comment]
I'm sorry I was not available during the last week,
I've noticed you've closed the issue with [this commit](https://github.com/nolimits4web/swiper/commit/cc2cd0b90039ea785c8e86f2b7c743727184efc6).
I don't know if it's in the dist build right now.
But I will check out your commit and update you with the result of your efforts. If it didn't still fix the bug in chrome with touch display laptops, we'll have to find a common ground on how my fix was doing what is needed and help you refactor the code so it can fit in the project.

**Comment by mhshakouri** [comment]
OK, Lets discuss it.
Your commit did not fix it.
On a touch display laptop, using chrome, we still have the problem.
But what was the problem actually?
I assume there is a mis-understanding going on here about what the actual problems are.
First I'd like to point out to this fact that up to version 4.0.7 everything was fine, at least I'm aware of this point.
The Problem:
Device/Software: AnyTouch Display Desktop or laptop / Google Chrome
Issue: No Mouse drag event for the slides nor the scrollbar

Now talking about the difference of my code to yours, the thing is, the code you mentioned, `// Chrome goes here` it never gets fired on chrome.
The previous block of code in the if statement blocks the rest.
What I did was the best of my effort to logically prioritize these events.
I had it tested in all major browsers, including IE11,Edge,Chrome,FireFox,Safari and it worked fine.

I'm so interested to know if you ever are going to either merge my changes, or do a better approach your self, bcuz man it's something that was there before, working seamlessly, but with the recent 4.1 update it's gone.

Just consider this we are in big trouble here, people are widely using your code. It's a work of art, so if you event don't have time to refactor the code on your own, merging this fix I wrote might be a good help to others too.

**Comment by nolimits4web** [comment]
Ok, can you please modify https://github.com/nolimits4web/swiper/blob/master/src/components/core/events/index.js#L29 to the following:
```js
  if (process.env.TARGET !== 'desktop') {
    console.log(`Support touch: ${Support.touch}`)
    console.log(`Support pointer: ${Support.pointerEvents || Support.prefixedPointerEvents}`)
    if (!Support.touch && (Support.pointerEvents || Support.prefixedPointerEvents)) {
      console.log(1)
      target.addEventListener(touchEvents.start, swiper.onTouchStart, false);
      document.addEventListener(touchEvents.move, swiper.onTouchMove, capture);
      document.addEventListener(touchEvents.end, swiper.onTouchEnd, false);
    } else {
      console.log(2)
      if (Support.touch) {
        console.log(3)
        const passiveListener = touchEvents.start === 'touchstart' && Support.passiveListener && params.passiveListeners ? { passive: true, capture: false } : false;
        target.addEventListener(touchEvents.start, swiper.onTouchStart, passiveListener);
        target.addEventListener(touchEvents.move, swiper.onTouchMove, Support.passiveListener ? { passive: false, capture } : capture);
        target.addEventListener(touchEvents.end, swiper.onTouchEnd, passiveListener);
      }
      if ((params.simulateTouch && !Device.ios && !Device.android) || (params.simulateTouch && !Support.touch && Device.ios)) {
        console.log(4)
        target.addEventListener('mousedown', swiper.onTouchStart, false);
        document.addEventListener('mousemove', swiper.onTouchMove, capture);
        document.addEventListener('mouseup', swiper.onTouchEnd, false);
      }
    }
    // Prevent Links Clicks
    if (params.preventClicks || params.preventClicksPropagation) {
      target.addEventListener('click', swiper.onClick, true);
    }
  } else {
    target.addEventListener('click', swiper.onClick, false);
  }
```
And tell me what you see in console?

**Comment by nolimits4web** [comment]
@mhshakouri can you check it?

**Comment by mhshakouri** [comment]
Sorry, I will check it within the next 24 hours.
I got so busy with a project.
I'll inform you soon.

**Comment by mhshakouri** [comment]
Here is the output:
```
Support touch: true
Support pointer: true
2
3
4
```
After I built the project using `npm run build:prod` it is working seamlessly with chrome on my surface pro 4 device. I pulled the latest version as of the time writing this reply.
but still the demo page on your own website is not working correctly as told before.

**Comment by mhshakouri** [comment]
I'll try the test again with a bare project

**Comment by mhshakouri** [comment]
Update:
I built the project, and tested the built swiper.js in a bare project and also the demos in the repo.
It's all working fine with your code on Surface/Chrome and using mouse drag.

the console output is:


`
swiper.js:2987             Support touch: true
swiper.js:2988             Support pointer: true
swiper.js:2995             2
swiper.js:2997             3
swiper.js:3004             4
`

Hopefully this seems to fix it:
https://github.com/nolimits4web/swiper/pull/2433#issuecomment-360967760

also the scrolldrag functionality work with mouse too.

**Comment by nolimits4web** [comment]
@mhshakouri thanks. This fix will be in next update then

**Pull request closed without merging**
