### PR TITLE
breakpoints source code fix, see issue https://github.com/nolimits4web/swiper/issues/2789

### PR DESCRIPTION
**Pull request by joejoseph00**
breakpoints parameters like spaceBetween and other breakpoint variables brought in sometimes as strings so the fix to this breakpoints responsive mode is to convert these variables to integers where appropriate (except 'auto' of course) so example slidesPerView and slidesPerGroup (I need this for breakpoints functionality) 
This is a pretty straight forward fix, have a look at the pull request and the commit.

I've also created a build in my fork, called it v4.4.2 of swiper. see my fork here: https://github.com/entreprise7pro/swiper

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks, but please remove all debug information and I will merge it

**Comment by joejoseph00** [comment]
@nolimits4web  , ok I have removed the debug information as requested.

**Comment by joejoseph00** [comment]
looks like still a couple minor issues the CI picked up on 
/home/travis/build/nolimits4web/swiper/src/components/core/breakpoints/setBreakpoint.js
  12:1    error  Trailing spaces not allowed          no-trailing-spaces
  17:49   error  Expected '===' and instead saw '=='  eqeqeq
  17:100  error  Expected '===' and instead saw '=='  eqeqeq

**Comment by joejoseph00** [comment]
ok @nolimits4web  I made also the ci fixes.

**Comment by nolimits4web** [comment]
Merged, thanks! I also tweaked it a bit to the following:

* slidesPerView can be `float`
* This part is not needed:
```
if (typeof breakPointsParams.slidesPerGroup !== 'undefined') {
      // Use the breakpoint slidesPerGroup, otherwise we'd get the default desktop setting.
      swiper.params.slidesPerGroup = breakPointsParams.slidesPerGroup;
    }
    if (typeof breakPointsParams.slidesPerView !== 'undefined') {
      // Use the breakpoint slidesPerView, otherwise we'd get the default desktop setting.
      swiper.params.slidesPerView = breakPointsParams.slidesPerView;
    }
    if (typeof breakPointsParams.spaceBetween !== 'undefined') {
      // Use the breakpoint spaceBetween, otherwise we'd get the default desktop setting.
      swiper.params.spaceBetween = breakPointsParams.spaceBetween;
    }
```

This is already done in `Utils.extend(swiper.params, breakpointParams);` above

**Pull request merged**
