### PR TITLE
Fixed can not get clicked slider in shadow root issue

### PR DESCRIPTION
**Pull request by yaoguoba**
Fixed can not get clicked slider in shadow root issue

### CODE REVIEW

**Comment by yaoguoba** [comment]
#5223

**Comment by nolimits4web** [comment]
- `event.path` is not standard property
- I guess `e.path[0]` you pass to updateClickedSlide is an Element, so accessing `e.target` in `updateClickedSlide` will be anyway undefined

**Comment by yaoguoba** [comment]
Sorry, I forgot to change updateClickedSlide.
Do you mean we can't use e.path here, I saw e.path used in onTouchStart.

Anyway, I will check the other way and will update later.

**Comment by yaoguoba** [comment]
Hi @nolimits4web, 

Event.composedPath is a standard equivalent which is a method.
Please check.

**Comment by nolimits4web** [comment]
merged, thanks!

**Pull request merged**
