### PR TITLE
simplifies code contributions by fully automating dev setup with Gitpod.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face:

This PR simplifies code contributions by automating the dev setup with Gitpod(A free online VS Code like IDE), with a single click it will launch a workspace and automatically: 

- clone the swiper repo.
- install the dependencies.
- run `npm run dev`

So that anyone interested in contributing can start straight away.

It seems to work well. You can give it a try on my fork of the repo via the link below:

https://gitpod.io/#https://github.com/nisarhassan12/swiper

image

### CODE REVIEW

**Comment by KristerV** [comment]
I gave this a go, although having such a lock-in to a random service seems peculiar.

Service takes so long to load I'm not sure if I wouldn't rather just clone and use the demos to figure it out myself. With my shortcuts.

Anyway the idea is interesting. If you want any traction with this - I suggest you make the default page load the demos, not a "3000 doesn't respond" message. In that case I could (theoretically) jump in and fix a bug.

**Comment by nisarhassan12** [comment]
Thanks, @KristerV :slightly_smiling_face: 

> I gave this a go, although having such a lock-in to a random service seems peculiar.

The goal for this PR is not to lock people in the goal is to simplify contributors onboarding by fully automating the dev environments.

> Service takes so long to load I'm not sure if I wouldn't rather just clone and use the demos to figure it out myself. With my shortcuts.

It's true that the loading should be as fast as possible. How long does it take for you? For me, it took about 20 seconds.

Accidently you might have got unlucky and was assigned a brand new server that wasn't ready (when it says "Acquiring Node ...", it can take a minute for the new server to be ready). It's a bad experience, but it's fairly rare and we're working on making this much faster

> Anyway the idea is interesting. If you want any traction with this - I suggest you make the default page load the demos, not a "3000 doesn't respond" message. In that case, I could (theoretically) jump in and fix a bug.

I have made the default page load `/demos/` this is how it looks: 

image

**Comment by vltansky** [comment]
`npm run dev` on gitpod fails.
```
 Watching file changes ...
[1] fs.js:1521
[1]     throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
[1]     ^
[1] 
[1] TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[1]     at Object.watch (fs.js:1521:11)
[1]     at Object.<anonymous> (/workspace/swiper/scripts/watch.js:14:4)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[1]     at internal/main/run_main_module.js:17:47 {
[1]   code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
[1] }
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! swiper-src@6.3.5 watch:dev: `cross-env NODE_ENV=development node scripts/watch`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the swiper-src@6.3.5 watch:dev script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/gitpod/.npm/_logs/2021-01-22T16_57_11_947Z-debug.log
[1] npm run watch:dev exited with code 1
--> Sending SIGTERM to other processes..
[0] 
[0] INFO: Gracefully shutting down. Please wait...
[0] npm run serve exited with code SIGTERM
```

**Comment by nisarhassan12** [comment]
@vltansky Thanks for reporting this. It was due to the node version upgrade I have now downgraded it and it works well.

**Pull request closed without merging**
