### PR TITLE
Add slideable menu demo

### PR DESCRIPTION
**Pull request by kireerik**
I have created a slideable menu using Swiper. I think it can be useful for the community as well. This demo can also demonstrate well that Swiper can be used in a wide range.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Looks cool, thanks, merged

**Comment by kireerik** [comment]
You are welcome!

Are you planning to add it to the official [Swiper Demos page](http://idangero.us/swiper/demos/)?
I think others would appreciate it as well.

**Comment by nolimits4web** [comment]
Yeah, will add it with next update

**Comment by kireerik** [comment]
Thank you so much!

I really love using Swiper in many of my own projects, because it provides huge variety of usecases!  It is a really robust framework. It can be even used for things we might not even think for the first time like a fully accessible slideable menu.
On one of my [commercial website](https://thebestarcadescript.com/) I use this menu "system" with some additional functionalities such as an "on left edge hover preview" feature. Plus it also has scroll detection, which closes the menu when needed.
On request I will might add these little tweaks to this basic demo as well.

I highly appreciate your hard work with Swiper! So thank you for your business!

Good luck with your projects!

**Pull request merged**
