### PR TITLE
Fix: Add type support for Swiper/React ref object

### PR DESCRIPTION
**Pull request by dasilvaluis**
**Problem:**

When using Swiper/React with Typescript, and when one attempts to assign a ref to the Swiper component, TS gives an error similar to this:

```
Type '{ children: Element[]; ref: RefObject<any>; className: string; }' is not assignable to type 'IntrinsicAttributes & SwiperProps & { children?: ReactNode; }'. Property 'ref' does not exist on type 'IntrinsicAttributes & SwiperProps & { children?: ReactNode; }'
```

This was also discussed in this issue: https://github.com/nolimits4web/swiper/issues/5241

**Solution:**

This happens because, although the Swiper component uses forwardRef, it is not defined in the .d.ts file.

The proposal is to create an interface that represents the element injected in the ref, such as
```ts
interface SwiperRef extends React.HTMLAttributes<HTMLElement> {
  swiper: SwiperClass;
}
```

And use it in the Swiper `declare` with `React.RefAttributes`, this way:

```ts
declare const Swiper: React.FunctionComponent<React.RefAttributes<SwiperRef> & SwiperProps>;
```
**Usage:**

With this solution in place, devs could then use the `SwiperRef` in such a way:

```ts
import React, { useRef } from 'react';
import { Swiper, SwiperRef, SwiperSlide } from 'swiper/react';

() => {
 const swiperRef = useRef<SwiperRef>(null);
 
 const swiperApi = swiperRef.current?.swiper;

  return (
    <Swiper ref={swiperRef}>
      <SwiperSlide>Hello1</SwiperSlide>
      <SwiperSlide>Hello2</SwiperSlide>
    </Swiper>
  );
};
```

### CODE REVIEW

**Comment by nolimits4web** [comment]
This is wrong as Swiper ref is a HTML Element, not an instance of Swiper

**Comment by nolimits4web** [comment]
Yes, missed that. Merged, thanks!

**Comment by ibrvimv** [comment]
Hi, I cannot find SwiperRef in swiper-react.d.ts. Should I install it? thanks

**Comment by omaxlive** [comment]
> 

Probably because it's still not released @ibrvimv 

Thank you @dasilvaluis for this PR. Do you know when is it expected to be released?

**Comment by dasilvaluis** [comment]
> > 
> 
> Probably because it's still not released @ibrvimv
> 
> Thank you @dasilvaluis for this PR. Do you know when is it expected to be released?

I don't know man, I'm just some other guy

**Comment by waleedcj** [comment]
swiperRef doesn't exist

**Comment by ilik666** [comment]
SwiperRef doesn't exist yet

**Comment by yusufcode** [comment]
Is there a solution on this case? I tried almost all the solutions but non of them worked. I'm working on create-react-app --template typescript. When I was working without --template typescript there was no problem like this.

**Comment by dasilvaluis** [comment]
@yusufcode hard to help without seeing your code.

**Comment by yusufcode** [comment]
@dasilvaluis hey man, thank you for return. Actually, there is no difference between typescripted and not typescripted codes. These are my codes:
```
<Swiper
        spaceBetween={24} // <- problem accours here
      >
        {
          swiperItems.map((swiperItem,i)=>
            <SwiperSlide key={i}>
              <Box display="flex" flexDir="column" bg="#fff" border="1px solid #E0D8D7" borderBottom="4px solid #ED1C24" borderRadius="2px">
                <Text>{swiperItem.title}</Text>
                <Text>{swiperItem.description}</Text>
                <Box>
                  <Button variant="second">Learn More</Button>
                  <Button variant="first">Find A Dealer</Button>
                </Box>
              </Box>
            </SwiperSlide>
          )
        }
      </Swiper>
```

By the way I SOLVED the problem. I downgraded the swiper from v10.0.4 to v9.4.1 and type problems gone. higher versions from v9.4.1  has these type problems. So I advise you guys to use lower versions of swiper.

**Pull request merged**
