### PR TITLE
feat(shadow): fix find wrapper

### PR DESCRIPTION
**Pull request by ghaiat**
Fix swiper for use with shadow dom components

### CODE REVIEW

**Comment by nolimits4web** [comment]
Can you please keep formatting? Right now it is not possible to understand where changes made

**Comment by nolimits4web** [comment]
Also can you please provide a minimal example of the usecase which it fixes?

**Comment by ghaiat** [comment]
@nolimits4web done. sorry for the mess

basically the use case is if the element is a shadow dom element, you cannot query directly children, you have to use shadowRoot
the code is just checking if the el has a shadowRoot or not

**Comment by nolimits4web** [comment]
You mean when Swiper used as a web component which includes wrapper and you pass slides elements as slots?

**Comment by ghaiat** [comment]
yes

**Comment by nolimits4web** [comment]
Merged, thanks!

**Comment by ghaiat** [comment]
thanks, could you trigger a new release so i can test on my app ?
cheers

**Comment by taoqf** [comment]
I need a example too.
I find it's difficult to use swiper in shadowdom.

```ts
const tpl = `
<link href="//cdn.jsdelivr.net/npm/swiper@5.2.1/css/swiper.css" rel="stylesheet">
<div class="swiper-container">
	<!-- Additional required wrapper -->
	<div class="swiper-wrapper">
		<slot></slot>
	</div>
	<!-- If we need pagination -->
	<div class="swiper-pagination"></div>

	<!-- If we need navigation buttons -->
	<div class="swiper-button-prev"></div>
	<div class="swiper-button-next"></div>

	<!-- If we need scrollbar -->
	<div class="swiper-scrollbar"></div>
</div>
`;

export default class MySwiper extends HTMLElement {
	private dom: ShadowRoot;
	constructor() {
		super();
		this.dom = this.attachShadow({ mode: 'open' }); // 1
		this.dom.innerHTML = tpl;
	}

	public async connectedCallback() {
		const root = this;
		// const root = this.dom.querySelector<HTMLElement>('.swiper-container');  // 2
		const nextEl = this.dom.querySelector<HTMLElement>('.swiper-button-next')!;
		const prevEl = this.dom.querySelector<HTMLElement>('.swiper-button-prev')!;
		new Swiper(root!, {
			navigation: {
				nextEl,
				prevEl
			}
		});
	}
}

window.customElements.define('my-swiper', MySwiper);
```

1. `el && el.shadowRoot` will be null if mode is `closed`;
1. `el && el.shadowRoot` will be null too if I use `swiper-container`.

**Pull request merged**
