### PR TITLE
fix slide prev bug when using loop with slidesPerGroup and slidesPerView

### PR DESCRIPTION
**Pull request by johnson0903**
Please see #2875 
I modify index.html in playground for demo usage.
Fix this bug through plus snapIndex 1 when total slides can't divide by slidePerGroup when call slideTo by loopFix

### CODE REVIEW

**Comment by nolimits4web** [comment]
Hi! Can you please provide a demo with latest Swiper 7 with the issue this PR fixes?

**Comment by johnson0903** [comment]
Hi, there is it. [https://johnson0903.github.io/swiper/playground/core/](url)

**Comment by nolimits4web** [comment]
Thanks, but as I see with the fix it is still works kind of incorrect, I guess expected behavior is:
Initial: [1, 2, 3]
Press back: [8,9,10]
Press back: [5, 6, 7], but we see here [7,8,9]

Problem is somewhere deeper I think, and also there is a [`loopFillGroupWithBlank`](https://swiperjs.com/swiper-api#param-loopFillGroupWithBlank) which supposed to be used when number of slides not even to slidesPerGroup

**Comment by johnson0903** [comment]
I think if you want to display [5,6,7], you have to update snap grids during fixloop, because the snap grids is set to [8,9,10][1,2,3][4,5,6][7,8,9][10,1,2][1,2,3] in loop mode when initialize swiper in this situation ,there is no [5,6,7] . But if update snap grids, you can't go back to [1,2,3] because it will become [5,6,7] -> [4,3,2]. 
I think maybe change [10,1,2] to [8,9,10] when initialize can be another solution.

**Pull request closed without merging**
