### PR TITLE
dynamic bullets: multiple main bullets

### PR DESCRIPTION
**Pull request by tzvikaf**
Hi,
right now the dynamic bullets in the pagination are limited to one active and 4 more, 2 for each side.
i added code to have more main bullets instead of just one, 
it feels more smooth when there is room for the active bullet to move in.

i'm using your code in a mobile-web project at my company
and i would really like if the code would become part of the package instead of me using locally the modified version.

i'll be happy to hear any comments,
have a nice day,
tzvika

### CODE REVIEW

**Comment by tzvikaf** [comment]
use example:
var swiper = new Swiper('.swiper-container', {
      pagination: {
        el: '.swiper-pagination',
        dynamicBullets: {
          numOfMainBullets: 4
        }
      },
    });

**Comment by nolimits4web** [comment]
Looks good, thanks! I did some small renaming and fixed lastIndex calculation, was wrong a bit

**Comment by tzvikaf** [comment]
thanks :)

**Comment by tzvikaf** [comment]
what about documentation?

**Comment by nolimits4web** [comment]
Will be update with new version release. If you want to add it then PR is welcome to https://github.com/nolimits4web/swiper-website

**Comment by tzvikaf** [comment]
cool, i'll prepare something till the weekend

**Pull request merged**
