### PR TITLE
feat(core): swiping in `rewind` mode

### PR DESCRIPTION
**Pull request by vltansky**
closes https://github.com/nolimits4web/swiper/issues/5361

not sure if the new parameter is needed or it just should work this way always in rewind mode.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Look at how it works in issue's Glide example link, it does rewind during swipe not on release, so it should happen within onTouchMove handler

**Comment by vltansky** [comment]
Ok, will refactor it.
But should it be a parameter?
I think no..

**Comment by nolimits4web** [comment]
It should consider touch direction and swipe ratio/duration. To avoid such cases:

https://user-images.githubusercontent.com/999588/152800276-42587612-baa7-4a09-ba8d-02a15ccedab7.mov

On first slide it should rewind to last on swipe if:
- swipe direction is `prev` + touch duration is more than `params.longSwipesMs` + swipe ratio `>= params.longSwipesRatio`
- swipe direction is `prev` + touch duration is less than `params.longSwipesMs`

same for rewind on last slide

**Comment by vltansky** [comment]
How about this approach ?

**Comment by nolimits4web** [comment]
Nothing changed as I see:

https://user-images.githubusercontent.com/999588/153372436-de11286d-a57e-4f10-bea3-b6e3eb203312.mov

**Pull request merged**
