### PR TITLE
feat(angular): index control

### PR DESCRIPTION
**Pull request by vltansky**
```html

  <swiper [(index)]="indexNumber" [pagination]="{ type: 'fraction' }">
    <ng-template swiperSlide>Best slide ever 1</ng-template>
    <ng-template swiperSlide>Best slide ever 2</ng-template>
    <ng-template swiperSlide>Best slide ever 3</ng-template>
  </swiper>
  <button (click)="indexNumber = 0">0</button>
  <button (click)="indexNumber = 3">3</button>
  <button (click)="indexNumber = 5">5</button>
  <button (click)="indexNumber = 6">6</button>
   {{ indexNumber}}
```

### CODE REVIEW

**Comment by vltansky** [comment]
This PR based on https://github.com/nolimits4web/swiper/pull/4028
I wanted to create this PR as draft (forgot).

**Comment by vltansky** [comment]
@nolimits4web this is ready to be reviewed / merged.
Do you want to rename it maybe? `[(index)]` to `[(slideIndex])` or something else?

**Comment by nolimits4web** [comment]
I think `(index)` is fine. Is it ready to be merged?

Btw, why I didn't add such extra API "wrapping" for other frameworks because basically it is possible to use `swiper` instance for this, and I am afraid that users will ask to add such functionality for other core API methods, which will produce a bunch of code duplication. So if we add this one, let it be the only one 😄

**Comment by vltansky** [comment]
Yeah, it's ready to be merged.

Got it :)

**Comment by nolimits4web** [comment]
Thanks, merged!

**Pull request merged**
