### PR TITLE
Add features section to readme

### PR DESCRIPTION
**Pull request by vltansky**
Maybe we should add all modules here?

### CODE REVIEW

**Comment by vltansky** [comment]
@nolimits4web guess the list can be improved & more modules can be added?

**Comment by nolimits4web** [comment]
@vltansky you mean modules like Navigation, Pagination, etc.? What is missing, I guess worth mention is Virtual and maybe Zoom modules. All other basically covered in existing list in some way

**Comment by vltansky** [comment]
Guess we should extract this bullet:
"And many more ...: All Swiper well-known features are also here: Responsive, Scroll prevention, Resistant bounds, Autoplay, Loop mode, Nested Swipers" to multiple. As loop mode, nested swipers, Autoplay, Scrollbar (+progress bar) also worth a bullet for each of them?

Also, I think we should add React, Vue, Svelte and Angular versions as features.

**Comment by nolimits4web** [comment]
@vltansky I agree :)

**Comment by vltansky** [comment]
I'll make a PR with additions.

**Pull request merged**
