### PR TITLE
Fix Issue #4272

### PR DESCRIPTION
**Pull request by faskade**
Fix Issue [#4272](https://github.com/nolimits4web/swiper/issues/4272)

### CODE REVIEW

**Comment by nolimits4web** [comment]
Can you elaborate a bit, as I don't understand, how and why this object becomes empty on iOS? :)

**Comment by faskade** [comment]
The object doesn't become empty. Everything okay with the object. But since it's some special reactive vue object it has some problems with methods like Object.keys(). Object.keys(props) returns an empty array instead of the key's array on IOS. At least on my iphone.

**Comment by nolimits4web** [comment]
Ok, merged, thanks!

**Comment by Saltibarsciai** [comment]
Hey, @nolimits4web  when are you planning to release this? 
I have such prop `:navigation="{ nextEl: '.nextArrow--c', prevEl: '.prevArrow--c' }"` but on iphone 6 arrows do nothing, I think this pull request fixes it (on other phones it works)

**Pull request merged**
