### PR TITLE
Fix freeMode + mousewheel + loop

### PR DESCRIPTION
**Pull request by elaman**
With `freeMode` and `loop` are enabled, `mousewheel` component doesn't respect those parameters. This will fix it, by using the `slideTo` method, to move back/forward from **duplicate** slide to **real** one.

Note: Changes are made to the latest commit. `npm run build:prod` had been run after changing `mousewheel` component file.

Pull request must fix this issue #2210.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Hi, thanks. But changes to `dist/` files shouldn't be submitted. Also PR must pass lint tests https://travis-ci.org/nolimits4web/swiper/builds/356416021?utm_source=github_status&utm_medium=notification

**Comment by nolimits4web** [comment]
Ok, better now, thanks. But from what i see and quick tests it doesn't fix the problem. Evenmore with `slidesPerView: 1` mousewheel doesn't work at all.

**Comment by nolimits4web** [comment]
There is a more simple fix for this by calling just `fixLoop()` for the free mode

**Comment by elaman** [comment]
Thanks for `fixLoop()`

**Pull request closed without merging**
