### PR TITLE
Use ResizeObserver polyfill for resize instead of window.resize.

### LINKED ISSUE #2068: Resizing on container resize instead of window resize
This is a (multiple allowed):
* [x] bug
* [x] enhancement

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: All platforms

### What you did
After a `window.resize` a css animation is triggered on the parent container and the slider size is not updated appropriately.

### Expected Behavior
Slider's width updates appropriately given the updated container width.

### Actual Behavior
Slider's width stays at the width of after the `window.resize`, not after the container width change upon css animation.

### PR DESCRIPTION
**Pull request by AO16**
- Fixes #2068 
- Added in ResizeObserver pollyfill
- Observe container for resize instead of window
- Added polyfill to gulp build

https://github.com/que-etc/resize-observer-polyfill

### CODE REVIEW

**Comment by nolimits4web** [comment]
Closing as outdated and incompatible with current version of Swiper

**Comment by omar10594** [comment]
@AO16  The issue still exists on 4.0.2

**Comment by Pablodotnet** [comment]
@nolimits4web What if instead of closing it just make it compatible with the current version of Swiper? Because the issue is still there...

**Comment by AO16** [comment]
I'd be willing to put together another pull request if this is something @nolimits4web is willing to pull in

**Pull request closed without merging**
