### PR TITLE
Simplify Preloader CSS

### PR DESCRIPTION
**Pull request by Rikk**

### CODE REVIEW

**Comment by nolimits4web** [comment]
I mean it here:) is it cross browser?

**Comment by Rikk** [comment]
There's no mention of incomplete support of the `animation-timing-function` property (the one responsible for `steps(x,end)`).
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
http://caniuse.com/#feat=css-animation
https://docs.webplatform.org/wiki/css/properties/animation-timing-function
IE10+ is said to support it fully: https://msdn.microsoft.com/en-us/library/ie/hh772240.aspx

**Comment by nolimits4web** [comment]
Sorry, commits should be made in dist folder, i will move it there

**Comment by nolimits4web** [comment]
Ok, it is good in all browsers, thanks

**Pull request merged**
