### PR TITLE
Fixed Multi Row Lazy loading and Multi Row order

### PR DESCRIPTION
**Pull request by bhaniel**
Fixed the issue with the multi row bug.
And also the Multi Row order when choosing fill "Row" to be :+1: 
1 | 2 | 3
4 | 5|  6
7 | 8 | 9

### CODE REVIEW

**Comment by zorn-v** [comment]
With 6 items order like a mess
1 | 3
2 | 6
4 | 5

**Comment by eddneal** [comment]
Hi all, is this PR being considered? It would really help with a project I am working on.

**Comment by donnielaur** [comment]
This is a big issue for me, I can't use the slider if it can not do columns and row order properly.  I see the fixes, but how do I get it in a simple swiper.js file?

**Comment by nolimits4web** [comment]
Closing as outdated and incompatible with current version of Swiper

**Pull request closed without merging**
