### PR TITLE
cleanup dynamic styles, classNames and autoPlay upon destroy

### PR DESCRIPTION
**Pull request by mrtnbroder**

### CODE REVIEW

**Comment by nolimits4web** [comment]
Accepted, thanks, but cleaning up styles and classes should be optional, will add it

**Comment by mrtnbroder** [comment]
awesome thanks, it's probably missing some cleanup still on buttons or something, you know that better than I do ;)

My pleasure!

**Comment by nolimits4web** [comment]
Yep, and i'll probably merge cleanUpStyles and detachClassNames funcions to one, to save some code lines :) As i don't think that there could be such situation when they needed separately

**Comment by nolimits4web** [comment]
Ok, merged two funcs, also added cleanup for buttons, and better check for pagination and scrollbar elements. And i made it optional, it will not cleanup styles by default as really not always required

**Comment by mrtnbroder** [comment]
:+1: 

planning on updating the version soon? :)

**Comment by nolimits4web** [comment]
Probably on weekend

**Pull request merged**
