### PR TITLE
Fix issue 3928, should not lazy load when swiper not inView.

### PR DESCRIPTION
**Pull request by ygj6**
Fix issue #3928.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Hi! Like the idea, but it is not so easy here. What I think:
- First of all it should be configurable (and disabled by default) not to introduce breaking/different behavior for existing setups
- Checking `window.scroll` is not a valid for all the cases as Swiper can be in some inner element with `overflow: auto`. So "scrolling element" should be also configurable (with defaults to window/document) that should be considered for offsets/scroll calculations

**Comment by ygj6** [comment]
Yes, you're right, I've overlooked these details. I will take some time to look at it again.

**Comment by ygj6** [comment]
How about always checking `window.onscroll` by default?

**Comment by nolimits4web** [comment]
Thanks! I just pushed couple of fixes, so now it will listen for scroll only on one element, `window` or any custom specified. Also `onscroll` should not be used as it can be easily overwritten by user.

**Comment by Hirbod** [comment]
@nolimits4web @ygj6  this changes are missing in the documentation.
And don't you think using an IntersectionObserver might be a better and performant solution? Listening to scroll events is not the right thing to do anymore imho.

**Comment by Hirbod** [comment]
And why is it disabled when `loop` is true

**Pull request merged**
