### PR TITLE
add support lazy load for picture with source

### PR DESCRIPTION
**Pull request by exdeniz**
Add support lazyload for picture element with source tag.

### CODE REVIEW

**Comment by nolimits4web** [comment]
Please, only changes to `src` files are allowed. Remove any changes to `dist` files and i will merge it

**Comment by bpeab** [comment]
Is there any release date for that feature ?

**Comment by exdeniz** [comment]
> Please, only changes to `src` files are allowed. Remove any changes to `dist` files and i will merge it

done

**Comment by bpeab** [comment]
@exdeniz It seems that your solution also download the fallback image (the source inside the `` element) but from my understanding, it shouldn't be the case. Only the defined viewport source should be downloaded, thus only one image should be downloaded. Wdyt?

**Comment by bpeab** [comment]
@exdeniz Also, it doesn't work at all with IE 11 even with Picturefull acting as a polyfill when `<picture>` isn't natively supported.

**Comment by exdeniz** [comment]
> @exdeniz It seems that your solution also download the fallback image (the source inside the `` element) but from my understanding, it shouldn't be the case. Only the defined viewport source should be downloaded, thus only one image should be downloaded. Wdyt?

If use ```<source srcset="..."/>``` and `````` browser load a picture in ```<source ...>``` anyway. Need use ```<source data-srcset="..."/>``` for correct load picture. This patch fixes this. For more detail see https://github.com/verlok/lazyload

**Comment by exdeniz** [comment]
> @exdeniz Also, it doesn't work at all with IE 11 even with Picturefull acting as a polyfill when `<picture>` isn't natively supported.

If you use `<picture>`, then you know about polyfill.

**Comment by bpeab** [comment]
Have you testing on IE11 yourself ? It just doesn't work with Picturefill. It always base itself on the fallback image. I have lazySizes enabled on all other images and it works perfectly with Picturefill but with Swiper and the changes you've made, it calculates the height based on the fallback image.

**Comment by exdeniz** [comment]
> Have you testing on IE11 yourself ? It just doesn't work with Picturefill. It always base itself on the fallback image. I have lazySizes enabled on all other images and it works perfectly with Picturefill but with Swiper and the changes you've made, it calculates the height based on the fallback image.

I have no way to test and fix this on IE11

**Comment by bpeab** [comment]
Ok. I am investiguating since I really need this feature. `source` seem to be completly ignored once lazy-loaded. Can't really find why. I have some base64 png as `srcset` before making the switch with the image and the height seems right (it takes the good viewport one) but once lazy-loaded, it doesn't work at all... I'll keep searching...

**Comment by exdeniz** [comment]
> Ok. I am investiguating since I really need this feature. `source` seem to be completly ignored once lazy-loaded. Can't really find why. I have some base64 png as `srcset` before making the switch with the image and the height seems right (it takes the good viewport one) but once lazy-loaded, it doesn't work at all... I'll keep searching...

Stop using IE11 =)

**Comment by bpeab** [comment]
I found a work-around. It'll be in a PR later today.

> Stop using IE11 =)

That would be nice but unfortunatly not negociable 😄

**Comment by bpeab** [comment]
I submitted a PR (#3151) with the necessary changes to support the `picture` element lazy-loading and the ability to use Picturefill if it is available. 

@exdeniz @nolimits4web Let me know if it's okay or if something is missing.

**Comment by knynkwl** [comment]
Any idea if `<source>` will be supported?

**Pull request closed without merging**
