### PR TITLE
fix: postinstall echo on windows

### LINKED ISSUE #3985: Line breaks can't be quoted on Windows
I want to install swiper with npm on a Laravel project.
But I get the following error:

> npm ERR! Line breaks can't be quoted on Windows
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\hamed\AppData\Local\npm-cache\_logs\2020-11-28T14_07_10_351Z-debug.log

**I tried to install other packages with npm and succeeded**

and this is my error log:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\hamed\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'swiper',
0 verbose cli   '--save-dev'
0 verbose cli ]
1 info using npm@7.0.12
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 0ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:P:\server\www\porsino\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\hamed\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 verbose npm-session b48091502a798d9b
20 timing npm:load Completed in 20ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 675ms
23 timing idealTree:userRequests Completed in 3ms
24 silly idealTree buildDeps
25 silly fetch manifest swiper@*
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/swiper 1254ms (from cache)
28 silly placeDep ROOT swiper@6.3.5 OK for:  want: *
29 silly fetch manifest dom7@^3.0.0-alpha.7
30 silly fetch manifest ssr-window@^3.0.0-alpha.4
31 http fetch GET 304 https://registry.npmjs.org/dom7 315ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/ssr-window 700ms (from cache)
33 timing idealTree:#root Completed in 1966ms
34 silly placeDep ROOT dom7@3.0.0 OK for: swiper@6.3.5 want: ^3.0.0-alpha.7
35 silly placeDep ROOT ssr-window@3.0.0 OK for: swiper@6.3.5 want: ^3.0.0-alpha.4
36 timing idealTree:node_modules/swiper Completed in 6ms
37 timing idealTree:node_modules/dom7 Completed in 0ms
38 timing idealTree:node_modules/ssr-window Completed in 0ms
39 timing idealTree:buildDeps Completed in 1973ms
40 timing idealTree:fixDepFlags Completed in 11ms
41 timing idealTree Completed in 2687ms
42 timing reify:loadTrees Completed in 2688ms
43 timing reify:diffTrees Completed in 30ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 0ms
46 timing reify:createSparse Completed in 4ms
47 timing reify:loadBundles Completed in 0ms
48 timing reifyNode:node_modules/ssr-window Completed in 70ms
49 timing reifyNode:node_modules/dom7 Completed in 78ms
50 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 433ms
51 timing auditReport:getReport Completed in 438ms
52 timing auditReport:init Completed in 0ms
53 timing reify:audit Completed in 440ms
54 timing reifyNode:node_modules/swiper Completed in 647ms
55 timing reify:unpack Completed in 647ms
56 timing reify:unretire Completed in 0ms
57 timing build:queue Completed in 1ms
58 info run swiper@6.3.5 postinstall node_modules/swiper echo "[35m[1mLove Swiper? Support Vladimir's work by donating or pledging on patreon:[22m[39m
58 info run  > [32mhttps://patreon.com/vladimirkharlampidi[0m
58 info run "
59 info run swiper@6.3.5 postinstall { code: undefined, signal: undefined }
60 timing reify:rollback:createSparse Completed in 0ms
61 timing reify:rollback:retireShallow Completed in 0ms
62 timing command:install Completed in 3385ms
63 verbose stack Error: Line breaks can't be quoted on Windows
63 verbose stack     at quoteForCmd (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\puka\index.js:41:11)
63 verbose stack     at Formatter.quote (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\puka\index.js:256:12)
63 verbose stack     at quoteForShell (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\puka\index.js:743:34)
63 verbose stack     at C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\make-spawn-args.js:13:90
63 verbose stack     at Array.map (<anonymous>)
63 verbose stack     at escapeCmd (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\make-spawn-args.js:13:75)
63 verbose stack     at makeSpawnArgs (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\make-spawn-args.js:37:43)
63 verbose stack     at runScriptPkg (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:54:29)
63 verbose stack     at runScript (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:16)
63 verbose stack     at Array.<anonymous> (C:\Users\hamed\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:264:17)
64 verbose cwd P:\server\www\porsino
65 verbose Windows_NT 10.0.19042
66 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hamed\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "swiper" "--save-dev"
67 verbose node v15.2.1
68 verbose npm  v7.0.12
69 error Line breaks can't be quoted on Windows
70 verbose exit 1
```

### PR DESCRIPTION
**Pull request by vltansky**
closes  #3985 
looks like echo with \n is failing in postinstall script on windows.

In windows 10 it's not crashing but it's not writing the second line:
```
$ npm run postinstall

> swiper@6.4.1 postinstall D:\projects\swiper\package
> echo "Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi
"

"Love Swiper? Support Vladimir's work by donating or pledging on patreon:
```
On Windows NT and probably other old windows versions its crashes.
echo ** & echo ** should work fine on both platforms I think.

### CODE REVIEW

**Comment by vltansky** [comment]
Don't merge this yet. Looks like this isn't solving the problem.
https://github.com/nolimits4web/swiper/issues/3985#issuecomment-742721434

**Comment by vltansky** [comment]
As echo didn't work, I thought that the best cross-platform here is NodeJS console.log()

First I made inline script:
```js
"postinstall": "node -e \"console.log('\u001b[35m\u001b[1m','Love Swiper? Support Vladimir\\'s work by donating or pledging on patreon:');console.log('\u001b[22m\u001b[39m\u001b[32m','> https://patreon.com/vladimirkharlampidi');\""
```
but that's how it looks like in output, the message kind of duplicated (echo looks the same way by the way):
```
> swiper@6.4.1 postinstall D:\projects\swiper\package
> node -e "console.log('','Love Swiper? Support Vladimir\'s work by donating or pledging on patreon:');console.log('','> https://patreon.com/vladimirkharlampidi');"

 Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi
```

So I thought it will be cleaner to move it into `postinstall.js`. Looks much better as for me:
```
> swiper@6.4.1 postinstall D:\projects\swiper\package
> node ./postinstall.js

 Love Swiper? Support Vladimir's work by donating or pledging on patreon:
 > https://patreon.com/vladimirkharlampidi
```

**Comment by nolimits4web** [comment]
> So I thought it will be cleaner to move it into postinstall.js. Looks much better as for me:

Makes sense to put `postinstall.js`, but will it run properly as it is installed as dependency and maybe it will try to look file in CWD (e.g. in project root that uses Swiper and not in swiper package itself), this needs to be checked

**Comment by vltansky** [comment]
https://unpkg.com/browse/node-sass@5.0.0/package.json
node-sass does the same.
Pretty sure it means its ok

**Comment by nolimits4web** [comment]
Ok, let's go with this way then

**Comment by nolimits4web** [comment]
@vltansky didn't we decided to go with node script here? 😄

**Comment by vltansky** [comment]
@nolimits4web I was sure that this is what PR includes. Now I got why you didn't merge it after you told OK...
a merge from master overrode all the changes.
I'll make a new PR now with the relevant code.

Sorry about that. Will be more careful.

**Pull request merged**
