### PR TITLE
Add support for picture element lazy-loading

### PR DESCRIPTION
**Pull request by zhiru**
Add support for picture element lazy-loading.

I've made some changes on lazy.js to accept data-srcset like used on other pull request example.

Based on #3151 
Maybe solving #3096 #3112 

Test Use: https://aloje.com.br

### CODE REVIEW

**Comment by anthonycook** [comment]
Great job! Hope this get's merged soon, I've been using a third party lazy-loading plugin just to get it working with the picture element. 🙈

**Comment by zhiru** [comment]
temporary i've used too, this [Lazyload Lib](https://github.com/verlok/lazyload), but i'm thinking of closing this and re-open, i find another adjust that refers to the same on problem.

i need other one to check if is correct and working, can you test the last two commits @anthonycook ?

[ Commits Swiper](https://github.com/zhiru/swiper/commits/master)

**Comment by nolimits4web** [comment]
Thanks! I pushed some minor tweaks, seems to be works fine

**Comment by JamesIves** [comment]
Is there an example of this available in documentation somewhere? From what I can tell you need to attach `class="swiper-lazy"` to each `source` element that is a child of `picture` too? (The following is using Angular so the `attr.` prefix is needed or it will render it as `srcset` directly. 

<picture class="storefront-banner__background-container--asset">
   <source class="swiper-lazy" media="(min-width: 300px)" attr.data-srcset="..." />
   <source class="swiper-lazy" media="(min-width: 600px)" attr.data-srcset="..." />
   
</picture>

**Comment by maddocnc** [comment]
> Is there an example of this available in documentation somewhere? From what I can tell you need to attach `class="swiper-lazy"` to each `source` element that is a child of `picture` too? (The following is using Angular so the `attr.` prefix is needed or it will render it as `srcset` directly.
> 

Looks like you need data-srcset on source, and swiper-lazy class only on  it then takes it's parent <picture> and do the job.

**Pull request merged**
